# -*- coding: utf-8 -*-
"""PythonII

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sW-run9wG5GxnIYRNaOggbCoHi6UgS0m

SECTION A

1)Write a python program to print "Hello Python"
"""

def myfun():
   a="Hello Python"
   print(a)
myfun()

"""2)Write a python program to do arithmetical operations addition and division"""

a=int(input("Enter the value:"))
b=int(input("Enter the value:"))
sum=a+b
print(sum)
div=a/b
print(div)

"""3)Write a python program to find area of triangle

"""

base=float(input("Enter the base value:"))
height=float(input("Enter the height value:"))
area=0.5*base*height
print("Area of Triangle=",area)

"""4)Write a python program to swap two variables"""

a=10
b=20
temp=a
a=b
b=temp
print("Value of a=",a)
print("value of b=",b)

"""5)Write a python program to generate a random number"""

import random
print(random.randint(0,9))

"""SECTION B

1)Write a python program to convert kilometer to miles
"""

KM=int(input("Enter the kilometer value:"))
Miles=0.621*KM
print("Kilometer=",KM,"Miles=",Miles)

"""2)Write a python program to convert celsius to Fahrenheit"""

celsius=float(input("Enter the celsius value:"))
fahrenheit=(celsius*9/5)+32
print("Celsius=",celsius,"Fahrenheit=",fahrenheit)

"""3)Write a python program to display calendar"""

import calendar
y=2022
m=8
print(calendar.month(y,m))

"""4)Write a python program to solve quadratic equation

"""

import cmath
a = 2
b = 2
c = 3
d = (b**2) - (4*a*c)
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print(sol1,sol2)

"""5)Write a python program to solve two variables without temp. variables"""

a=8
b=3
a=a+b
b=a-b
a=a-b
print("a=",a,"b=",b)

"""SECTION C

1)Write a Python Program to Check if a Number is Positive, Negative or Zero?
"""

num=int(input("Enter the value:"))
if num>0:
   print("Positive Number")
elif num<0:
   print("Negative Numeber")
else:
   print("zero")

"""2)Write a Python Program to Check if a Number is Odd or Even?"""

num=int(input("Enter the value:"))
if num%2==0:
  print("It is Even")
else:
  print("It is odd")

"""3)Write a Python Program to Check Leap Year?"""

year=int(input("Enter the year:"))
if (year % 400 == 0) and (year % 100 == 0):
    print("This is a leap year")
elif (year % 4 ==0) and (year % 100 != 0):
    print("This is a leap year")
else:
    print("This is not a leap year")

"""4)Write a Python Program to Check Prime Number?"""

num=int(input("Enter the value:"))
if num > 1:
    for i in range(2, int(num/2)+1):
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

"""5)Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?"""

lower=int(input("Enter the loer range:"))
upper=int(input("Enter the upper range:"))
print("Prime numbers between", lower, "and", upper, "are:")
for num in range(lower, upper + 1):  
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

"""SECTION D

1)Write a Python Program to Find the Factorial of a Number?
"""

def fact(n):
  fact=1
  for i in range(1,n+1):
    fact=fact*i
  print(fact)  
fact(6)

"""2)Write a Python Program to Display the multiplication Table?"""

num=int(input("Multiplication table of:"))
for i in range(1, 11):
   print(num, 'x', i, '=', num*i)

"""3)Write a Python Program to Print the Fibonacci sequence"""

a=0
b=1
print(a)
print(b)
for i in range(1,11):
  c=a+b
  a=b
  b=c
  print(c)

"""4)Write a Python Program to Check Armstrong Number?"""

num = int(input("Enter a number: "))
sum = 0
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

"""5)Write a Python Program to Find Armstrong Number in an Interval?"""

lower=int(input("Enter lower range:"))
upper=int(input("Enter upper range:"))
for i in range(lower,upper+1):
  sum=0
  num=i
  while(i!=0):
    digit=i%10
    sum=sum+(digit*digit*digit)
    i=i//10
  if sum==num:
     print(num)

"""6)Write a Python Program to Find the Sum of Natural Numbers?"""

num=int(input("Enter the value:"))
if num < 0:
   print("Enter a positive number")
else:
   sum = 0
   while(num > 0):
       sum += num
       num -= 1
   print("The sum is", sum)

"""SECTION E

1)Write a Python Program to find sum of array?
"""

array=[6,4,3,2,1]
sum=0
for num in array:
  sum=sum+num
print(sum)

"""2)Write a Python Program to find largest element in an array?"""

a = [10,20,30,40]
max_element = a[0]
for i in range(len(a)):
  if a[i] > max_element:
     max_element = a[i]

print (max_element)

"""3)Write a Python Program for array rotation?"""

def rotateArray(a,d):
    n=len(a)
    a[:]=a[d:n]+a[0:d]
    return a
arr = [3,4,5,6,8,9,1]
print("Rotated list is")
print(rotateArray(arr,2))

"""4)Write a Python Program to Split the array and add the first part to the end?"""

def SplitArray(arr, n, k):
	for i in range(0, k):
		x = arr[0]
		for j in range(0, n-1):
			arr[j] = arr[j + 1]		
		arr[n-1] = x		
arr = [1,2,3,4,5,6]
n = len(arr)
position = 3
SplitArray(arr, n, position)
for i in range(0, n):
	print(arr[i], end = ' ')

"""5)Write a Python Program to check if given array is Monotonic?"""

def ismonotone(a):
    n=len(a) #size of array
    if n==1:
        return True
    else:       
        if all(a[i]>=a[i+1] for i in range(0,n-1) or a[i]<=a[i+1] for i in range(0,n-1)):
            return True
        else:
            return False
A = [6, 5, 4, 2]
print(ismonotone(A))

"""SECTION F

1)Write a Python program to find sum of elements in list?
"""

def sumlist(list):
    sum=0
    for i in range(len(list)):
        sum = sum+list[i]
    return sum
list = [20,40,60]
print(list)
print("sum of list: ",sumlist(list))

"""2)Write a Python program to Multiply all numbers in the list?"""

def mul_list(list) :         
    product = 1
    for i in list:
         product = product * i
    return product     
list1 = [1,2,3,4]
print(list1)
print("product: ") 
print(mul_list(list1))

"""3,4)Write a Python program to find smallest and largest number in a list?"""

a=(6,9,8,5,4)
print(a)
max_number=max(a)
print(max_number)
min_number=min(a)
print(min_number)

"""5)Write a Python program to find second largest number in a list?"""

list1 = [90,80,50,30]
new_list = set(list1)
new_list.remove(max(new_list))
print(max(new_list))

"""6)Write a Python program to find N largest elements from a list?"""

def LargestFunc(list1, N):
	new_list = []
	for i in range(0, N):
		max1 = 0
		for j in range(len(list1)):
			if list1[j] > max1:
				max1 = list1[j];
		list1.remove(max1);
		new_list.append(max1)
	print("Largest numbers = ",new_list)
my_list = [12, 61, 41, 85, 40, 13, 77, 65, 100]
N = 2
LargestFunc(my_list, N)

"""7)Write a Python program to print even numbers in a list?"""

list1 = [10, 21, 4, 45, 66, 93]
for num in list1:
    if num % 2 == 0:
       print(num, end=" ")

"""8)Write a Python program to print odd numbers in a List?"""

list1 = [10, 21, 4, 45, 66, 93]
for num in list1:
    if num % 2 != 0:
       print(num, end=" ")

"""9)Write a Python program to Remove empty List from List?"""

test_list = [5, 6, [], 3, [], [], 9]
print("The original list is : " + str(test_list))
while [] in test_list :
    test_list.remove([])
print("List after empty list removal : " + str(test_list))

"""10)Write a Python program to Cloning or Copying a list?"""

def Cloning(a1):
    li_copy = a1[:]
    return li_copy
a1 = [4, 8, 2, 10, 15, 18]
a2 = Cloning(a1)
print("Original List:", a1)
print("After Cloning:", a2)

"""11)Write a Python program to Count occurrences of an element in a list?"""

sample_list = ["2", "4", "2", "8", "2", "8"]
print(sample_list.count("2"))